name: Bump Universal Cross Training Script Version
on:
  schedule:
    - cron: '0 10 * * 1-5'
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install requests
      - name: Bump Gist version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 'e0bf2670bf5b474e9f7017b116d5bd22'
        run: python update_script.py
